import turtle as trtl

painter = trtl.Turtle()

painter.penup()
painter.goto(-100, 175)
painter.pendown()
painter.forward(185)
painter.right(105)
painter.forward(50)
painter.setheading(180)
painter.forward(155)
painter.goto(-100, 175)
painter.penup()
painter.goto(-84, 127)
painter.pendown()
painter.pensize(5)
painter.forward(60)
painter.left(90)
painter.forward(150)
painter.left(90)
painter.forward(275)
painter.left(90)
painter.forward(150)
painter.left(90)
painter.forward(225)
painter.penup()
painter.goto(-5, -7)
painter.pendown()
painter.pencolor("green")
painter.write("EXIT", move=False, align="center", font=("Arial", 100, "bold"))
painter.hideturtle()


wn = trtl.Screen()
wn.mainloop()